USE ROLE SYSADMIN;
USE WAREHOUSE TEST;
USE DATABASE PLAYGROUND_LM;
USE SCHEMA PUBLIC;

CREATE TABLE IF NOT EXISTS AGENT_INSIGHTS (
    INSIGHT_ID STRING,
    INSIGHT_DATA VARIANT,
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);
